<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOeVLeZd\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOeVLeZd/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerOeVLeZd.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerOeVLeZd\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerOeVLeZd\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'OeVLeZd',
    'container.build_id' => '6180cc3d',
    'container.build_time' => 1620032908,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOeVLeZd');
